# -*- coding: utf-8 -*-
"""app2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xFS2YuD3TdK8dH7tH_o1suXwzoXc5ftG
"""

import streamlit as st
import pandas as pd
import pickle
import plotly.graph_objects as go

# -----------------------------
# PAGE CONFIG
# -----------------------------
st.set_page_config(
    page_title="Placement Trend Analyzer",
    page_icon="🎓",
    layout="wide"
)

# -----------------------------
# LOAD MODELS
# -----------------------------
placement_model = pickle.load(open("placement_model.pkl", "rb"))
salary_model = pickle.load(open("salary_model.pkl", "rb"))

# -----------------------------
# SIDEBAR
# -----------------------------
st.sidebar.title("🎓 Placement Trend Analyzer")

st.sidebar.markdown("### Project Overview")
st.sidebar.info(
    """
    This dashboard predicts:

    ✅ Placement Status

    ✅ Expected Salary Package

    using Machine Learning models trained on student academic and technical profiles.
    """
)

st.sidebar.markdown("### Model Performance")

st.sidebar.success(
    """
    Placement Model

    Accuracy: 69.8%
    """
)

st.sidebar.success(
    """
    Salary Model

    R² Score: 78.4%
    """
)

st.sidebar.markdown("---")

st.sidebar.markdown(
    """
    **Technologies Used**

    - Python
    - Streamlit
    - Scikit-Learn
    - XGBoost
    - Plotly
    """
)

# -----------------------------
# TITLE
# -----------------------------
st.title("🎓 Student Placement & Salary Prediction Dashboard")

st.markdown(
    "Predict placement opportunities and expected salary packages using Machine Learning."
)

st.markdown("---")

# -----------------------------
# INPUT SECTION
# -----------------------------
st.header("📋 Student Profile")

col1, col2 = st.columns(2)

with col1:
    
     branch_options = {
        "Computer Science Engineering (CSE)": 0,
        "Information Technology (IT)": 1,
        "Electronics & Communication (ECE)": 2,
        "Electrical Engineering (EEE)": 3,
        "Mechanical Engineering": 4,
        "Civil Engineering": 5,
        "Other Branch": 6
    }

    selected_branch = st.selectbox(
        "Branch",
        list(branch_options.keys())
    )
    
    branch = branch_options[selected_branch]
    
    college_tier = st.selectbox(
            "College Tier",
            [0, 1, 2],
            format_func=lambda x: f"Tier {x+1}"
        )
    
    cgpa = st.slider(
            "CGPA",
            0.0,
            10.0,
            7.0
        )
    
    backlogs = st.number_input(
            "Backlogs",
            min_value=0,
            max_value=20,
            value=0
        )
    
    internships = st.number_input(
            "Internships",
            min_value=0,
            max_value=20,
            value=1
        )
    
    projects_count = st.number_input(
            "Projects",
            min_value=0,
            max_value=50,
            value=2
        )

with col2:

    coding_skills = st.slider(
        "Coding Skills",
        0,
        100,
        70
    )

    dsa_score = st.slider(
        "DSA Score",
        0,
        100,
        70
    )

    aptitude_score = st.slider(
        "Aptitude Score",
        0,
        100,
        70
    )

    communication_skills = st.slider(
        "Communication Skills",
        0,
        100,
        70
    )

    certifications = st.number_input(
        "Certifications",
        min_value=0,
        max_value=50,
        value=2
    )

    hackathons = st.number_input(
        "Hackathons",
        min_value=0,
        max_value=50,
        value=1
    )

    open_source_contributions = st.number_input(
        "Open Source Contributions",
        min_value=0,
        max_value=100,
        value=0
    )

# -----------------------------
# PREDICTION BUTTON
# -----------------------------
if st.button("🚀 Predict"):

    # Hidden Features
    ml_knowledge = 5
    system_design = 5
    extracurriculars = 5

    input_df = pd.DataFrame({
        'branch': [branch],
        'college_tier': [college_tier],
        'cgpa': [cgpa],
        'backlogs': [backlogs],
        'coding_skills': [coding_skills],
        'dsa_score': [dsa_score],
        'aptitude_score': [aptitude_score],
        'communication_skills': [communication_skills],
        'ml_knowledge': [ml_knowledge],
        'system_design': [system_design],
        'internships': [internships],
        'projects_count': [projects_count],
        'certifications': [certifications],
        'hackathons': [hackathons],
        'open_source_contributions': [open_source_contributions],
        'extracurriculars': [extracurriculars]
    })

    # -------------------------
    # PREDICTIONS
    # -------------------------

    placement_prediction = placement_model.predict(input_df)[0]

    probability = placement_model.predict_proba(input_df)[0]

    placement_probability = probability[1] * 100

    salary_prediction = salary_model.predict(input_df)[0]

    # -------------------------
    # RESULTS
    # -------------------------

    st.markdown("---")
    st.header("📊 Prediction Results")

    metric1, metric2 = st.columns(2)

    with metric1:

        if placement_prediction == 1:
            st.success("✅ Likely to be Placed")
        else:
            st.error("❌ Placement Probability is Low")

        st.metric(
            "Placement Probability",
            f"{placement_probability:.1f}%"
        )

    with metric2:

        st.metric(
            "Expected Salary Package",
            f"{salary_prediction:.2f} LPA"
        )

        if salary_prediction < 5:
            st.info("💼 Entry Level Package")

        elif salary_prediction < 10:
            st.success("📈 Good Package")

        elif salary_prediction < 15:
            st.success("🚀 Excellent Package")

        else:
            st.success("🏆 Premium Package")

    # -------------------------
    # DONUT CHART
    # -------------------------

    st.subheader("🎯 Placement Probability")

    fig = go.Figure(
        data=[
            go.Pie(
                labels=["Placed", "Not Placed"],
                values=[
                    placement_probability,
                    100 - placement_probability
                ],
                hole=0.65
            )
        ]
    )

    fig.update_layout(height=450)

    st.plotly_chart(
        fig,
        use_container_width=True
    )

    # -------------------------
    # RADAR CHART
    # -------------------------

    st.subheader("📈 Skill Profile")

    categories = [
        "Coding",
        "DSA",
        "Aptitude",
        "Communication",
        "CGPA"
    ]

    values = [
        coding_skills,
        dsa_score,
        aptitude_score,
        communication_skills,
        cgpa * 10
    ]

    radar = go.Figure()

    radar.add_trace(
        go.Scatterpolar(
            r=values,
            theta=categories,
            fill='toself',
            name='Student Profile'
        )
    )

    radar.update_layout(
        polar=dict(
            radialaxis=dict(
                visible=True,
                range=[0, 100]
            )
        ),
        showlegend=False,
        height=500
    )

    st.plotly_chart(
        radar,
        use_container_width=True
    )

# -----------------------------
# FOOTER
# -----------------------------
st.markdown("---")

st.markdown(
    """
    ### About

    This dashboard was developed as a Machine Learning project to analyze student placement trends and predict salary packages based on academic performance, technical skills, internships, projects, and extracurricular achievements.
    """
)

st.markdown(
    "Built with ❤️ using Streamlit, Scikit-Learn, XGBoost and Plotly."
)
